spring:
  h2:
    console.enabled: true
    console.path: /h2
    console.settings.trace : false
    spring.h2.console.settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    driverClassName: org.h2.Driver